#ifndef BOOTSTRAP_CMDS_COMPAT_NON_APPLE_MACH_BOOLEAN_H_
#define BOOTSTRAP_CMDS_COMPAT_NON_APPLE_MACH_BOOLEAN_H_

typedef int boolean_t;

#define TRUE 1
#define FALSE 0

#endif  /* BOOTSTRAP_CMDS_COMPAT_NON_APPLE_MACH_BOOLEAN_H_ */
